services:
  workspace:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/home/developer/ros2_ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev:/dev
      - /dev/input/js*:/dev/input/js*
      - /dev/input/event*:/dev/input/event*
      - "/dev/bus/usb:/dev/bus/usb"   # RealSense
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB3:/dev/ttyUSB3
      - /dev/ttyUSB4:/dev/ttyUSB4
      - /dev/video*:/dev/video*
    group_add:
      - plugdev
      - video
    user: developer
    ports:
      - "5000:5000"
    environment:
      # - DISPLAY
      - "QT_X11_NO_MITSHM=1"